# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use the official Python image from the Docker Hub
FROM python:3.11-slim

# Install uv
# COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
RUN pip install uv

# Enable bytecode compilation
ENV UV_COMPILE_BYTECODE=1

# Copy dependencies and install dependencies **as non-root**
COPY . . 

RUN uv pip install --system -e .

# Expose the default port for SSE transport
EXPOSE 8000

# Environment variable for the Kagi API key
ENV HYPERSPELL_TOKEN="USER OR APP TOKEN"
# Run the MCP server
# ENTRYPOINT ["uv", "run", "hyperspell_mcp"]
# ENTRYPOINT ["python", "-v", "-m", "hyperspell_mcp"]
CMD ["python", "-m", "hyperspell_mcp"]