[project]
name = "hyperspell_mcp"
version = "0.1.0"
description = "Hyperspell MCP Server"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "hyperspell>=0.5.3",
    "mcp[cli]>=1.4.1",
]
